### ISSUE TITLE
resources fails with make-handler?

### ISSUE THREAD

**Issue by marianoguerra** [juxt/bidi#99]
create project

    lein new bidiresources
    cd bidiresources

    mkdir -p resources/public/
    echo "hello world" > resources/public/index.html

projects.clj

    (defproject bidiresources "0.1.0-SNAPSHOT"
      :description "FIXME: write description"
      :url "http://example.com/FIXME"
      :license {:name "Eclipse Public License"
                :url "http://www.eclipse.org/legal/epl-v10.html"}
      :main bidiresources.core
      :dependencies [[org.clojure/clojure "1.7.0"]
                     [bidi "1.21.1"]
                     [org.immutant/web "2.1.1"]])

bidiresources/core.clj

    (ns bidiresources.core
      (:require
        [bidi.ring :refer [make-handler resources]]
        [immutant.web :as web])
      (:gen-class))

    (def req-handlers {:resources (resources {:prefix "public/"})})
    (def routes ["/ui" (resources {:prefix "public/"})])
    (def app (make-handler routes req-handlers))

    (defn -main []
      (web/run app))

Doing

    curl -v http://localhost:8080/ui/index.html

Fails with:

    java.lang.IllegalArgumentException: No implementation of method: :request of protocol: #'bidi.ring/Ring found for class: nil
            at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554) ~[clojure-1.7.0.jar:na]
            at bidi.ring$eval2571$fn__2572$G__2562__2581.invoke(ring.clj:13) ~[na:na]
            at bidi.ring$make_handler$fn__2601.invoke(ring.clj:39) ~[na:na]
            at immutant.web.internal.undertow$create_http_handler$reify__6011.handleRequest(undertow.clj:135) ~[na:na]
            at org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:104) ~[wunderboss-web-undertow-0.10.0.jar:na]
            at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:778) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]

if I change

    (def routes ["/ui" (resources {:prefix "public/"})])

for

    (def routes ["/ui" :resources])

I get

    java.lang.NullPointerException: Ring handler returned nil
            at immutant.web.internal.undertow$create_http_handler$reify__6011.handleRequest(undertow.clj:138) ~[na:na]
            at org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:104) ~[wunderboss-web-undertow-0.10.0.jar:na]
            at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:778) ~[undertow-core-1.3.0.Beta9.jar:1.3.0.Beta9]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]

**Comment by malcolmsparks** [comment]
Hi, can you let me know which version of bidi is this?




Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by malcolmsparks** [comment]
If you change

```clojure
(def app (make-handler routes req-handlers))
```

to 

```clojure
(def app (make-handler routes))
```

it should work. The optional second parameter to `make-handler` must be a function (or something that can be called like a function, e.g. a map) which must return a Ring handler function (or satisfy bidi's Ring protocol). The Resources record doesn't qualify on both counts, that's why it fails.

It is possible for me to update the Resources, ResourcesMaybe and Files records to sastisfy bidi's Ring protocol. You could try with your own records and let me know if it works.

Sorry for the confusion.

**Comment by dazld** [comment]
@malcolmsparks I've been banging my head against this for a bit, and didn't realise that this was the problem! Is updating Resources / ResourcesMaybe etc to satisfy the ring protocol still something that could be done?
